// flow-typed signature: f85933aa7917f22789d543d5eec25a2f
// flow-typed version: <<STUB>>/bin-version_v4.0.0/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bin-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bin-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bin-version/index' {
  declare module.exports: $Exports<'bin-version'>;
}
declare module 'bin-version/index.js' {
  declare module.exports: $Exports<'bin-version'>;
}
