// flow-typed signature: 4515b5527230c3feabf5318adae01c17
// flow-typed version: <<STUB>>/builtin-modules_v3.1.0/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'builtin-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'builtin-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'builtin-modules/static' {
  declare module.exports: any;
}

// Filename aliases
declare module 'builtin-modules/index' {
  declare module.exports: $Exports<'builtin-modules'>;
}
declare module 'builtin-modules/index.js' {
  declare module.exports: $Exports<'builtin-modules'>;
}
declare module 'builtin-modules/static.js' {
  declare module.exports: $Exports<'builtin-modules/static'>;
}
