// flow-typed signature: bc19bc980afeab83b03a6d000dacefae
// flow-typed version: <<STUB>>/clear-module_v3.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clear-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clear-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'clear-module/index' {
  declare module.exports: $Exports<'clear-module'>;
}
declare module 'clear-module/index.js' {
  declare module.exports: $Exports<'clear-module'>;
}
