// flow-typed signature: c020941cb6d3087e7b276196f04e7dd5
// flow-typed version: <<STUB>>/dequeue_v^1.0.5/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dequeue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dequeue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dequeue/lib/dequeue' {
  declare module.exports: any;
}

declare module 'dequeue/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dequeue/lib/dequeue.js' {
  declare module.exports: $Exports<'dequeue/lib/dequeue'>;
}
declare module 'dequeue/lib/index' {
  declare module.exports: $Exports<'dequeue/lib'>;
}
declare module 'dequeue/lib/index.js' {
  declare module.exports: $Exports<'dequeue/lib'>;
}
