// flow-typed signature: 20f1f48d9bc5124dbc26a1a85086831e
// flow-typed version: <<STUB>>/elegant-spinner_v^1.0.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'elegant-spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'elegant-spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'elegant-spinner/index' {
  declare module.exports: $Exports<'elegant-spinner'>;
}
declare module 'elegant-spinner/index.js' {
  declare module.exports: $Exports<'elegant-spinner'>;
}
