// flow-typed signature: 20e988c7e1c4207cd2874de5948e7d72
// flow-typed version: <<STUB>>/eslint-plugin-playlyfe_v6.2.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-playlyfe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-playlyfe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-playlyfe/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/flowtype/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/es-latest' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/imports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/node-commonjs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/possible-errors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/strict-mode' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/stylistic-issues' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/variables' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/rules/class-property-no-use-before-define' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/rules/freeze-const-object' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/js/rules/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/json/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/json/processors/json' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/json/rules/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/json/rules/use-exact-dependency' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/prettier/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-empty-translation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-missing-id' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-undef-id' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-untranslated-string' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/utils/isLocaleFile' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react/configs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react/rules/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react/rules/react-jsx-pascal-case-patched' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/react/rules/react-style-no-numeric-string-value' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/relay/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/relay/rules/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/relay/rules/relay-no-missing-variable-in-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/plugins/testing/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/utils/renameConfigRules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/utils/renameRules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/utils/RuleTester' {
  declare module.exports: any;
}

declare module 'eslint-plugin-playlyfe/lib/utils/runRule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-playlyfe/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/flowtype/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/flowtype/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/best-practices.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/best-practices'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/es-latest.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/es-latest'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/imports.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/imports'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/node-commonjs.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/node-commonjs'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/possible-errors.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/possible-errors'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/strict-mode.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/strict-mode'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/stylistic-issues.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/stylistic-issues'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/configs/variables.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/configs/variables'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/rules/class-property-no-use-before-define.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/rules/class-property-no-use-before-define'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/rules/freeze-const-object.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/rules/freeze-const-object'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/js/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/js/rules/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/json/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/json/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/json/processors/json.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/json/processors/json'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/json/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/json/rules/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/json/rules/use-exact-dependency.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/json/rules/use-exact-dependency'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/prettier/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/prettier/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react-intl/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-empty-translation.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-empty-translation'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-missing-id.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-missing-id'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-undef-id.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-undef-id'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-untranslated-string.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/react-intl-no-untranslated-string'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/utils/isLocaleFile.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react-intl/rules/utils/isLocaleFile'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react/configs.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react/configs'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react/rules/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react/rules/react-jsx-pascal-case-patched.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react/rules/react-jsx-pascal-case-patched'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/react/rules/react-style-no-numeric-string-value.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/react/rules/react-style-no-numeric-string-value'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/relay/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/relay/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/relay/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/relay/rules/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/relay/rules/relay-no-missing-variable-in-props.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/relay/rules/relay-no-missing-variable-in-props'>;
}
declare module 'eslint-plugin-playlyfe/lib/plugins/testing/index.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/plugins/testing/index'>;
}
declare module 'eslint-plugin-playlyfe/lib/utils/renameConfigRules.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/utils/renameConfigRules'>;
}
declare module 'eslint-plugin-playlyfe/lib/utils/renameRules.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/utils/renameRules'>;
}
declare module 'eslint-plugin-playlyfe/lib/utils/RuleTester.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/utils/RuleTester'>;
}
declare module 'eslint-plugin-playlyfe/lib/utils/runRule.js' {
  declare module.exports: $Exports<'eslint-plugin-playlyfe/lib/utils/runRule'>;
}
