// flow-typed signature: 09ec0dfb2371d32ee92bd62872e38bc6
// flow-typed version: <<STUB>>/event-kit_v^2.5.3/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'event-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'event-kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'event-kit/dist/composite-disposable' {
  declare module.exports: any;
}

declare module 'event-kit/dist/disposable' {
  declare module.exports: any;
}

declare module 'event-kit/dist/emitter' {
  declare module.exports: any;
}

declare module 'event-kit/dist/event-kit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'event-kit/dist/composite-disposable.js' {
  declare module.exports: $Exports<'event-kit/dist/composite-disposable'>;
}
declare module 'event-kit/dist/disposable.js' {
  declare module.exports: $Exports<'event-kit/dist/disposable'>;
}
declare module 'event-kit/dist/emitter.js' {
  declare module.exports: $Exports<'event-kit/dist/emitter'>;
}
declare module 'event-kit/dist/event-kit.js' {
  declare module.exports: $Exports<'event-kit/dist/event-kit'>;
}
