// flow-typed signature: 65a0c238895f298ef6ba9581ece2dbf1
// flow-typed version: <<STUB>>/log4js_v^0.6.37/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log4js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'log4js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'log4js/double-stack' {
  declare module.exports: any;
}

declare module 'log4js/examples/example-connect-logger' {
  declare module.exports: any;
}

declare module 'log4js/examples/example-socket' {
  declare module.exports: any;
}

declare module 'log4js/examples/example' {
  declare module.exports: any;
}

declare module 'log4js/examples/flush-on-exit' {
  declare module.exports: any;
}

declare module 'log4js/examples/fromreadme' {
  declare module.exports: any;
}

declare module 'log4js/examples/hipchat-appender' {
  declare module.exports: any;
}

declare module 'log4js/examples/log-rolling' {
  declare module.exports: any;
}

declare module 'log4js/examples/logFaces-appender' {
  declare module.exports: any;
}

declare module 'log4js/examples/loggly-appender' {
  declare module.exports: any;
}

declare module 'log4js/examples/logstashUDP' {
  declare module.exports: any;
}

declare module 'log4js/examples/memory-test' {
  declare module.exports: any;
}

declare module 'log4js/examples/patternLayout-tokens' {
  declare module.exports: any;
}

declare module 'log4js/examples/slack-appender' {
  declare module.exports: any;
}

declare module 'log4js/examples/smtp-appender' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/categoryFilter' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/clustered' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/console' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/dateFile' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/file' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/fileSync' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/gelf' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/hipchat' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/logFacesAppender' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/loggly' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/logLevelFilter' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/logstashUDP' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/mailgun' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/multiprocess' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/slack' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/smtp' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/stderr' {
  declare module.exports: any;
}

declare module 'log4js/lib/connect-logger' {
  declare module.exports: any;
}

declare module 'log4js/lib/date_format' {
  declare module.exports: any;
}

declare module 'log4js/lib/debug' {
  declare module.exports: any;
}

declare module 'log4js/lib/layouts' {
  declare module.exports: any;
}

declare module 'log4js/lib/levels' {
  declare module.exports: any;
}

declare module 'log4js/lib/log4js' {
  declare module.exports: any;
}

declare module 'log4js/lib/logger' {
  declare module.exports: any;
}

declare module 'log4js/lib/streams/BaseRollingFileStream' {
  declare module.exports: any;
}

declare module 'log4js/lib/streams/DateRollingFileStream' {
  declare module.exports: any;
}

declare module 'log4js/lib/streams/index' {
  declare module.exports: any;
}

declare module 'log4js/lib/streams/RollingFileStream' {
  declare module.exports: any;
}

declare module 'log4js/test/categoryFilter-test' {
  declare module.exports: any;
}

declare module 'log4js/test/clusteredAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/configuration-test' {
  declare module.exports: any;
}

declare module 'log4js/test/configureNoLevels-test' {
  declare module.exports: any;
}

declare module 'log4js/test/connect-logger-test' {
  declare module.exports: any;
}

declare module 'log4js/test/consoleAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/date_format-test' {
  declare module.exports: any;
}

declare module 'log4js/test/dateFileAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/debug-test' {
  declare module.exports: any;
}

declare module 'log4js/test/fileAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/fileSyncAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/gelfAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/global-log-level-test' {
  declare module.exports: any;
}

declare module 'log4js/test/hipchatAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/layouts-test' {
  declare module.exports: any;
}

declare module 'log4js/test/levels-test' {
  declare module.exports: any;
}

declare module 'log4js/test/log-abspath-test' {
  declare module.exports: any;
}

declare module 'log4js/test/logFacesAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/logger-test' {
  declare module.exports: any;
}

declare module 'log4js/test/logging-test' {
  declare module.exports: any;
}

declare module 'log4js/test/logglyAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/logLevelFilter-test' {
  declare module.exports: any;
}

declare module 'log4js/test/logstashUDP-test' {
  declare module.exports: any;
}

declare module 'log4js/test/mailgunAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/multiprocess-test' {
  declare module.exports: any;
}

declare module 'log4js/test/newLevel-test' {
  declare module.exports: any;
}

declare module 'log4js/test/nolog-test' {
  declare module.exports: any;
}

declare module 'log4js/test/reloadConfiguration-test' {
  declare module.exports: any;
}

declare module 'log4js/test/setLevel-asymmetry-test' {
  declare module.exports: any;
}

declare module 'log4js/test/slackAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/smtpAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/stderrAppender-test' {
  declare module.exports: any;
}

declare module 'log4js/test/streams/BaseRollingFileStream-test' {
  declare module.exports: any;
}

declare module 'log4js/test/streams/DateRollingFileStream-test' {
  declare module.exports: any;
}

declare module 'log4js/test/streams/rollingFileStream-test' {
  declare module.exports: any;
}

declare module 'log4js/test/subcategories-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'log4js/double-stack.js' {
  declare module.exports: $Exports<'log4js/double-stack'>;
}
declare module 'log4js/examples/example-connect-logger.js' {
  declare module.exports: $Exports<'log4js/examples/example-connect-logger'>;
}
declare module 'log4js/examples/example-socket.js' {
  declare module.exports: $Exports<'log4js/examples/example-socket'>;
}
declare module 'log4js/examples/example.js' {
  declare module.exports: $Exports<'log4js/examples/example'>;
}
declare module 'log4js/examples/flush-on-exit.js' {
  declare module.exports: $Exports<'log4js/examples/flush-on-exit'>;
}
declare module 'log4js/examples/fromreadme.js' {
  declare module.exports: $Exports<'log4js/examples/fromreadme'>;
}
declare module 'log4js/examples/hipchat-appender.js' {
  declare module.exports: $Exports<'log4js/examples/hipchat-appender'>;
}
declare module 'log4js/examples/log-rolling.js' {
  declare module.exports: $Exports<'log4js/examples/log-rolling'>;
}
declare module 'log4js/examples/logFaces-appender.js' {
  declare module.exports: $Exports<'log4js/examples/logFaces-appender'>;
}
declare module 'log4js/examples/loggly-appender.js' {
  declare module.exports: $Exports<'log4js/examples/loggly-appender'>;
}
declare module 'log4js/examples/logstashUDP.js' {
  declare module.exports: $Exports<'log4js/examples/logstashUDP'>;
}
declare module 'log4js/examples/memory-test.js' {
  declare module.exports: $Exports<'log4js/examples/memory-test'>;
}
declare module 'log4js/examples/patternLayout-tokens.js' {
  declare module.exports: $Exports<'log4js/examples/patternLayout-tokens'>;
}
declare module 'log4js/examples/slack-appender.js' {
  declare module.exports: $Exports<'log4js/examples/slack-appender'>;
}
declare module 'log4js/examples/smtp-appender.js' {
  declare module.exports: $Exports<'log4js/examples/smtp-appender'>;
}
declare module 'log4js/lib/appenders/categoryFilter.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/categoryFilter'>;
}
declare module 'log4js/lib/appenders/clustered.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/clustered'>;
}
declare module 'log4js/lib/appenders/console.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/console'>;
}
declare module 'log4js/lib/appenders/dateFile.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/dateFile'>;
}
declare module 'log4js/lib/appenders/file.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/file'>;
}
declare module 'log4js/lib/appenders/fileSync.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/fileSync'>;
}
declare module 'log4js/lib/appenders/gelf.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/gelf'>;
}
declare module 'log4js/lib/appenders/hipchat.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/hipchat'>;
}
declare module 'log4js/lib/appenders/logFacesAppender.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/logFacesAppender'>;
}
declare module 'log4js/lib/appenders/loggly.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/loggly'>;
}
declare module 'log4js/lib/appenders/logLevelFilter.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/logLevelFilter'>;
}
declare module 'log4js/lib/appenders/logstashUDP.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/logstashUDP'>;
}
declare module 'log4js/lib/appenders/mailgun.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/mailgun'>;
}
declare module 'log4js/lib/appenders/multiprocess.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/multiprocess'>;
}
declare module 'log4js/lib/appenders/slack.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/slack'>;
}
declare module 'log4js/lib/appenders/smtp.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/smtp'>;
}
declare module 'log4js/lib/appenders/stderr.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/stderr'>;
}
declare module 'log4js/lib/connect-logger.js' {
  declare module.exports: $Exports<'log4js/lib/connect-logger'>;
}
declare module 'log4js/lib/date_format.js' {
  declare module.exports: $Exports<'log4js/lib/date_format'>;
}
declare module 'log4js/lib/debug.js' {
  declare module.exports: $Exports<'log4js/lib/debug'>;
}
declare module 'log4js/lib/layouts.js' {
  declare module.exports: $Exports<'log4js/lib/layouts'>;
}
declare module 'log4js/lib/levels.js' {
  declare module.exports: $Exports<'log4js/lib/levels'>;
}
declare module 'log4js/lib/log4js.js' {
  declare module.exports: $Exports<'log4js/lib/log4js'>;
}
declare module 'log4js/lib/logger.js' {
  declare module.exports: $Exports<'log4js/lib/logger'>;
}
declare module 'log4js/lib/streams/BaseRollingFileStream.js' {
  declare module.exports: $Exports<'log4js/lib/streams/BaseRollingFileStream'>;
}
declare module 'log4js/lib/streams/DateRollingFileStream.js' {
  declare module.exports: $Exports<'log4js/lib/streams/DateRollingFileStream'>;
}
declare module 'log4js/lib/streams/index.js' {
  declare module.exports: $Exports<'log4js/lib/streams/index'>;
}
declare module 'log4js/lib/streams/RollingFileStream.js' {
  declare module.exports: $Exports<'log4js/lib/streams/RollingFileStream'>;
}
declare module 'log4js/test/categoryFilter-test.js' {
  declare module.exports: $Exports<'log4js/test/categoryFilter-test'>;
}
declare module 'log4js/test/clusteredAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/clusteredAppender-test'>;
}
declare module 'log4js/test/configuration-test.js' {
  declare module.exports: $Exports<'log4js/test/configuration-test'>;
}
declare module 'log4js/test/configureNoLevels-test.js' {
  declare module.exports: $Exports<'log4js/test/configureNoLevels-test'>;
}
declare module 'log4js/test/connect-logger-test.js' {
  declare module.exports: $Exports<'log4js/test/connect-logger-test'>;
}
declare module 'log4js/test/consoleAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/consoleAppender-test'>;
}
declare module 'log4js/test/date_format-test.js' {
  declare module.exports: $Exports<'log4js/test/date_format-test'>;
}
declare module 'log4js/test/dateFileAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/dateFileAppender-test'>;
}
declare module 'log4js/test/debug-test.js' {
  declare module.exports: $Exports<'log4js/test/debug-test'>;
}
declare module 'log4js/test/fileAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/fileAppender-test'>;
}
declare module 'log4js/test/fileSyncAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/fileSyncAppender-test'>;
}
declare module 'log4js/test/gelfAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/gelfAppender-test'>;
}
declare module 'log4js/test/global-log-level-test.js' {
  declare module.exports: $Exports<'log4js/test/global-log-level-test'>;
}
declare module 'log4js/test/hipchatAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/hipchatAppender-test'>;
}
declare module 'log4js/test/layouts-test.js' {
  declare module.exports: $Exports<'log4js/test/layouts-test'>;
}
declare module 'log4js/test/levels-test.js' {
  declare module.exports: $Exports<'log4js/test/levels-test'>;
}
declare module 'log4js/test/log-abspath-test.js' {
  declare module.exports: $Exports<'log4js/test/log-abspath-test'>;
}
declare module 'log4js/test/logFacesAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/logFacesAppender-test'>;
}
declare module 'log4js/test/logger-test.js' {
  declare module.exports: $Exports<'log4js/test/logger-test'>;
}
declare module 'log4js/test/logging-test.js' {
  declare module.exports: $Exports<'log4js/test/logging-test'>;
}
declare module 'log4js/test/logglyAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/logglyAppender-test'>;
}
declare module 'log4js/test/logLevelFilter-test.js' {
  declare module.exports: $Exports<'log4js/test/logLevelFilter-test'>;
}
declare module 'log4js/test/logstashUDP-test.js' {
  declare module.exports: $Exports<'log4js/test/logstashUDP-test'>;
}
declare module 'log4js/test/mailgunAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/mailgunAppender-test'>;
}
declare module 'log4js/test/multiprocess-test.js' {
  declare module.exports: $Exports<'log4js/test/multiprocess-test'>;
}
declare module 'log4js/test/newLevel-test.js' {
  declare module.exports: $Exports<'log4js/test/newLevel-test'>;
}
declare module 'log4js/test/nolog-test.js' {
  declare module.exports: $Exports<'log4js/test/nolog-test'>;
}
declare module 'log4js/test/reloadConfiguration-test.js' {
  declare module.exports: $Exports<'log4js/test/reloadConfiguration-test'>;
}
declare module 'log4js/test/setLevel-asymmetry-test.js' {
  declare module.exports: $Exports<'log4js/test/setLevel-asymmetry-test'>;
}
declare module 'log4js/test/slackAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/slackAppender-test'>;
}
declare module 'log4js/test/smtpAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/smtpAppender-test'>;
}
declare module 'log4js/test/stderrAppender-test.js' {
  declare module.exports: $Exports<'log4js/test/stderrAppender-test'>;
}
declare module 'log4js/test/streams/BaseRollingFileStream-test.js' {
  declare module.exports: $Exports<'log4js/test/streams/BaseRollingFileStream-test'>;
}
declare module 'log4js/test/streams/DateRollingFileStream-test.js' {
  declare module.exports: $Exports<'log4js/test/streams/DateRollingFileStream-test'>;
}
declare module 'log4js/test/streams/rollingFileStream-test.js' {
  declare module.exports: $Exports<'log4js/test/streams/rollingFileStream-test'>;
}
declare module 'log4js/test/subcategories-test.js' {
  declare module.exports: $Exports<'log4js/test/subcategories-test'>;
}
