// flow-typed signature: 0ca7e6eed8dadd3885101e6f3f61614d
// flow-typed version: <<STUB>>/rollup-plugin-progress_v1.1.1/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-progress/dist/rollup-plugin-progress.esm' {
  declare module.exports: any;
}

declare module 'rollup-plugin-progress/dist/rollup-plugin-progress' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-progress/dist/rollup-plugin-progress.esm.js' {
  declare module.exports: $Exports<'rollup-plugin-progress/dist/rollup-plugin-progress.esm'>;
}
declare module 'rollup-plugin-progress/dist/rollup-plugin-progress.js' {
  declare module.exports: $Exports<'rollup-plugin-progress/dist/rollup-plugin-progress'>;
}
