// flow-typed signature: fabed94e94d78b92e3b66781f9dd61d0
// flow-typed version: <<STUB>>/semver_v^6.3.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semver/bin/semver' {
  declare module.exports: any;
}

declare module 'semver/semver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semver/bin/semver.js' {
  declare module.exports: $Exports<'semver/bin/semver'>;
}
declare module 'semver/semver.js' {
  declare module.exports: $Exports<'semver/semver'>;
}
