// flow-typed signature: 4bb37a058d34460966c72d5bc5ff1ee2
// flow-typed version: <<STUB>>/shell-quote_v^1.6.0/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shell-quote'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shell-quote' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shell-quote/example/env' {
  declare module.exports: any;
}

declare module 'shell-quote/example/op' {
  declare module.exports: any;
}

declare module 'shell-quote/example/parse' {
  declare module.exports: any;
}

declare module 'shell-quote/example/quote' {
  declare module.exports: any;
}

declare module 'shell-quote/test/comment' {
  declare module.exports: any;
}

declare module 'shell-quote/test/env_fn' {
  declare module.exports: any;
}

declare module 'shell-quote/test/env' {
  declare module.exports: any;
}

declare module 'shell-quote/test/op' {
  declare module.exports: any;
}

declare module 'shell-quote/test/parse' {
  declare module.exports: any;
}

declare module 'shell-quote/test/quote' {
  declare module.exports: any;
}

declare module 'shell-quote/test/set' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shell-quote/example/env.js' {
  declare module.exports: $Exports<'shell-quote/example/env'>;
}
declare module 'shell-quote/example/op.js' {
  declare module.exports: $Exports<'shell-quote/example/op'>;
}
declare module 'shell-quote/example/parse.js' {
  declare module.exports: $Exports<'shell-quote/example/parse'>;
}
declare module 'shell-quote/example/quote.js' {
  declare module.exports: $Exports<'shell-quote/example/quote'>;
}
declare module 'shell-quote/index' {
  declare module.exports: $Exports<'shell-quote'>;
}
declare module 'shell-quote/index.js' {
  declare module.exports: $Exports<'shell-quote'>;
}
declare module 'shell-quote/test/comment.js' {
  declare module.exports: $Exports<'shell-quote/test/comment'>;
}
declare module 'shell-quote/test/env_fn.js' {
  declare module.exports: $Exports<'shell-quote/test/env_fn'>;
}
declare module 'shell-quote/test/env.js' {
  declare module.exports: $Exports<'shell-quote/test/env'>;
}
declare module 'shell-quote/test/op.js' {
  declare module.exports: $Exports<'shell-quote/test/op'>;
}
declare module 'shell-quote/test/parse.js' {
  declare module.exports: $Exports<'shell-quote/test/parse'>;
}
declare module 'shell-quote/test/quote.js' {
  declare module.exports: $Exports<'shell-quote/test/quote'>;
}
declare module 'shell-quote/test/set.js' {
  declare module.exports: $Exports<'shell-quote/test/set'>;
}
