// flow-typed signature: 91a71dece578e9a8500848e67a37071b
// flow-typed version: <<STUB>>/vscode-languageclient_v^5.2.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-languageclient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-languageclient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-languageclient/lib/client' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/codeConverter' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/colorProvider' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/configuration' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/declaration' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/foldingRange' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/implementation' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/main' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/protocolCodeLens' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/protocolCompletionItem' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/protocolConverter' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/protocolDocumentLink' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/typeDefinition' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/utils/async' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/utils/is' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/utils/processes' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/utils/uuid' {
  declare module.exports: any;
}

declare module 'vscode-languageclient/lib/workspaceFolders' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-languageclient/lib/client.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/client'>;
}
declare module 'vscode-languageclient/lib/codeConverter.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/codeConverter'>;
}
declare module 'vscode-languageclient/lib/colorProvider.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/colorProvider'>;
}
declare module 'vscode-languageclient/lib/configuration.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/configuration'>;
}
declare module 'vscode-languageclient/lib/declaration.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/declaration'>;
}
declare module 'vscode-languageclient/lib/foldingRange.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/foldingRange'>;
}
declare module 'vscode-languageclient/lib/implementation.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/implementation'>;
}
declare module 'vscode-languageclient/lib/main.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/main'>;
}
declare module 'vscode-languageclient/lib/protocolCodeLens.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/protocolCodeLens'>;
}
declare module 'vscode-languageclient/lib/protocolCompletionItem.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/protocolCompletionItem'>;
}
declare module 'vscode-languageclient/lib/protocolConverter.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/protocolConverter'>;
}
declare module 'vscode-languageclient/lib/protocolDocumentLink.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/protocolDocumentLink'>;
}
declare module 'vscode-languageclient/lib/typeDefinition.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/typeDefinition'>;
}
declare module 'vscode-languageclient/lib/utils/async.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/utils/async'>;
}
declare module 'vscode-languageclient/lib/utils/is.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/utils/is'>;
}
declare module 'vscode-languageclient/lib/utils/processes.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/utils/processes'>;
}
declare module 'vscode-languageclient/lib/utils/uuid.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/utils/uuid'>;
}
declare module 'vscode-languageclient/lib/workspaceFolders.js' {
  declare module.exports: $Exports<'vscode-languageclient/lib/workspaceFolders'>;
}
