// flow-typed signature: c105a852a43075e82bc69f74f2d46944
// flow-typed version: <<STUB>>/vscode_v^1.1.21/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode/lib/shared' {
  declare module.exports: any;
}

declare module 'vscode/lib/testrunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode/lib/shared.js' {
  declare module.exports: $Exports<'vscode/lib/shared'>;
}
declare module 'vscode/lib/testrunner.js' {
  declare module.exports: $Exports<'vscode/lib/testrunner'>;
}
